version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: America/Sao_Paulo
  open-pull-requests-limit: 10
  target-branch: master
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: codemirror
    versions:
    - 5.59.1
    - 5.59.2
  - dependency-name: cytoscape
    versions:
    - 3.17.1
    - 3.18.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.3
    - 1.3.5
  - dependency-name: webpack
    versions:
    - 5.11.1
    - 5.19.0
  - dependency-name: "@fullcalendar/rrule"
    versions:
    - 5.5.0
  - dependency-name: "@fullcalendar/timegrid"
    versions:
    - 5.5.0
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: America/Sao_Paulo
  open-pull-requests-limit: 10
  target-branch: master
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: sabre/dav
    versions:
    - 4.1.4
  - dependency-name: rlanvin/php-rrule
    versions:
    - 2.2.1
  - dependency-name: symfony/console
    versions:
    - 4.4.18
